# Generated by Django 4.1.3 on 2023-03-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_name_category_en_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_category',
            field=models.CharField(help_text='category name', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_category_en_us',
            field=models.CharField(help_text='category name', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_category_ru',
            field=models.CharField(help_text='category name', max_length=64, null=True, unique=True),
        ),
    ]
